---
# tasks file for mytomrole
- name: install tomcat
  yum:
   name: tomcat
   state: present
  
- name:  copy tom config file into all nodes
  template:
    src:  templates/mytomconfig.j2
    dest: /usr/share/tomcat/conf/tomcat.conf
  notify: starttomcat

- name:  Install Admin Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps

- name: coy tom user file into all nodes
  template:
    src: templates/mytomusers.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restarttomcat

- name: deploy java application on all nodes
  get_url:
    url: http://52.90.17.232:8081/artifactory/ravipem2/1/target/raviLogin-1.0.war
    dest: /var/lib/tomcat7/webapps/raviLogin.war
    force_basic_auth: yes